### PR TITLE
set_images feature on put/out

### PR DESCRIPTION
**Pull request by x3nb63**
Here is another feature I needed along with the filtering.

My biggest touch on existing code is that the `kubectl` param of `out` had to become optional. Guess it does not matter as who uses it ... uses it. But I don't know.

README.md has two examples. The first could actually be achieved with the `kubectl` param alone. The second shows actual use.

`kubectl` and `set_images` should work complementary cause both can be specified at the same time. I have no use for it yet, but its possible.

### CODE REVIEW

**Comment by jgriff** [comment]
Thanks for the PR!

This seems a little kludgy to a very specific `kubectl` command (`kubectl set image`).  And it sets a pattern for an array of other future specific `kubectl` commands that would wind up in a growing if/else statements in our code. 

Can't you currently achieve the same goal with:
```yaml
        params:
          kubectl: set image deployment/my-database mysql=docker.io/mysql:5.7
```
Or did you have trouble doing it that way?


This change creates a condition where the `kubectl` config is now _Optional_, whereas currently it is _Required_ (and the primary param for `put`).  

The multiple `set_images` config also breaks away from the "Concoursey" paradigm of a single `out` command.  I would rather see that expressed as multiple `put` operations for the resource (or perhaps part of the new ["spaces"](https://github.com/vito/rfcs/blob/spatial-resources/029-across-step/proposal.md) support).

There's a lot of value in the simplicity and succinctness having a standard, well understood single config option for `kubectl`.  It's still powerful enough to run any `kubectl` command you want, without creating (potentially) 1:1 param support for any `kubectl` operation.

**Comment by x3nb63** [comment]
> Can't you currently achieve the same goal with:
> 
> ```yaml
>         params:
>           kubectl: set image deployment/my-database mysql=docker.io/mysql:5.7
> ```
> 
> Or did you have trouble doing it that way?

trouble no, if its a simple case as this then that is the easy way to go.

My actual problem is a application that consists of ~10 pods which pop out of a build pipeline as a set of 10 images (hashes) that need to be running on the cluster.  I must ensure to never ever mix hashes from two builds. Also the order matters, cause some pods may run data migrations on their volumes at startup...  so I wanted a bulky way of telling the cluster the set of images at once.... then I also need to tell that set of images to multiple clusters... so, this way, each `set_images` step in my pipeline refers to another cluster which makes them roll forward more-or-less simultaneously  (this makes multiple instances stay compatible to each other).

(note: these apps also utilize [probes](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes) to make K8s grant them time for migration work, which also leads to proper order of upgrade stuff in each cluster, depending on the workload at runtime)

Initial idea was to use this more advanced syntax of:

```
kubectl set image deployments,replicationcontroller,statefulset \
    <container-name-A>=<image-A-with-hash> \
    <container-name-B>=<image-B-with-hash> \
    ....
    <container-name-N>=<image-N-with-hash> \
    --all
```
in order to send everything in one API call to the cluster. This PR does not do this yet cause I cant really test it right now...

> This change creates a condition where the `kubectl` config is now _Optional_, whereas currently it is _Required_ (and the primary param for `put`).

yeah, I had no idea how to "noop" it so I made it skip when a empty string is given... cause I did not wanna break the `main()` function. So, yeah, now  a `put` without any argument would run, doing nothing and succeed with that.

> The multiple `set_images` config also breaks away from the "Concoursey" paradigm of a single `out` command. I would rather see that expressed as multiple `put` operations for the resource (or perhaps part of the new ["spaces"](https://github.com/vito/rfcs/blob/spatial-resources/029-across-step/proposal.md) support).

interesting, I did not spot these "spaces" yet. Is this already implemented? sounds like this other feature of "across" steps?

**Comment by jgriff** [comment]
Setting all images in one `kubectl` command requires you to first list all of the resources, then their `<container-name>=<new-image-id>`.  Also, `kubectl` is expecting all of those container names to exist in _every_ resource type you identify.

For example, if you have the following deployments and their container(s):
* `deployment-a` : `foo`, `bar`
* `deployment-b` : `foo`, `baz`

And you execute:
```
kubectl set image deployments \
  deployment-a deployment-b \
  foo=0.1.0 bar=0.1.0
```
You'll get an error for `bar` not being a container in `deployment-b` (which would be treated as a failure in your pipeline):
```
deployment.apps/deployment-a image updated
deployment.apps/deployment-a image updated
deployment.apps/deployment-b image updated
error: unable to find container named "bar"
```

My suggestion would be to issue these as individual `put` statements.  Treat them each as a distinct operation.
```yaml
      - put: deployment-a-image-update
        resource: k8s
        params:
          kubectl: set image deployment/deployment-a foo=((.:foo-digest)) bar=((.:bar-digest))
      - put: deployment-b-image-update
        resource: k8s
        params:
          kubectl: set image deployment/deployment-b foo=((.:foo-digest)) baz=((.:baz-digest))
```
This would also give you deterministic ordering of the image updates.

However, if you wanted to "batch" them, you could parallelize the steps.
```yaml
      in_parallel:
        - put: deployment-a-image-update
          ...
        - put: deployment-b-image-update
          ...
```

**Comment by x3nb63** [comment]
> You'll get an error for `bar` not being a container in `deployment-b` (which would be treated as a failure in your pipeline):

yeah, thats a problem. Suspected something here, thanks for trying.

I think I could catch this specific error cause I know which combinations of controller and container are desired, .... thats some work tough. Will look at that.

> My suggestion would be to issue these as individual put statements.

I re-wrote my production pipeline to try this, and yes, it works.

my problems with that are:

- the yaml ends up larger and with very long lines (given our image names and variables derived from that ...)
- its hard to grasp on the WebUI: the `put` steps do not show the hashes, so its a lot of clicking to see whats been rolled... in `set_images` I made it show a count of how many changes were made and in the output it shows a block of text almost like a table
- its slower

All quite specific, yes, but since I now have it, I'll keep using it and update the PR with improvements I make - unless you don't want me to.

**Comment by jgriff** [comment]
I agree probably the most painful part with multiple `put` steps is the dramatically increased time it takes to run (creating a unique container for each `put`).

I thought for a bit about perhaps turning the `kubectl` param into a list.  This would help with the batching (run them all in the same `put` step).  Something like:

```yaml
      - put: k8s
        params:
          kubectl:
            - set image deployment/deployment-a foo=((.:foo-digest)) bar=((.:bar-digest))
            - set image deployment/deployment-b foo=((.:foo-digest)) baz=((.:baz-digest))
```
But moves into a gray area of `put` no longer being a single, atomic, and idempotent `step`.

## Concourse Spaces

However, this is the motivation for [spaces](https://github.com/vito/rfcs/blob/spatial-resources/029-across-step/proposal.md).  If the current trajectory holds, your use case might be serviced using the proposed `across` step.  Perhaps something like:

```yaml
      - across:
        - var: image-update
          values:
            - deployment/deployment-a foo=((.:foo-digest)) bar=((.:bar-digest))
            - deployment/deployment-b foo=((.:foo-digest)) baz=((.:baz-digest))
        do:
          - put: k8s
            params:
              kubectl: set image ((.:image-update))
```

## Path Forward

I sympathize with your unique use case, but I feel the way it's currently implemented adds complexity (and a little uncertainty treating `kubectl` as _optional_) for a very specific use case.

> All quite specific, yes, but since I now have it, I'll keep using it and update the PR with improvements I make - unless you don't want me to.

Given the reasons above, I'm going to close this.  If we come up with a cleaner solution for custom `kubectl` commands, let's definitely revisit this.

Thanks again for the work and feedback!

**Pull request closed without merging**
